### ISSUE TITLE
Output Transform

### ISSUE THREAD

**Issue by ghost** [lassoan/SlicerElastix#5] opened 2018-01-24 21:08 UTC
I was trying to get output transform in generic rigid registration, but it doesn't record any output transform. Although I get the output volume, I don't know what is the output transform :(

**Comment by lassoan** [comment] 2018-01-24 21:20
Create an output transform node (not linear transform but simply Transform node, as Elastix always returns the transform as a displacement field) and then you should get the transform as well.

Unfortunately, Elastix saves resulting transformation into proprietary Elastix transformation file instead of a standard ITK registration file. Therefore, currently we can only access transformation as a displacement field.

We [asked Elastix developers to implement saving into standard ITK format](https://github.com/SuperElastix/elastix/issues/18) but it seems to be a non-trivial task and they would like us to work on that.

Probably the simplest way of getting transforms from Elastix is to implement parsing of Elastix transform files in Slicer. It would be probably enough to implement reading of a linear and bspline transforms.

**Comment by lassoan** [comment] 2019-08-10 02:06
@prash-p I've implemented reading of bspline transforms. So now composite transforms made up of Euler, Translation, and Bspline transforms can be read directly into Slicer (no need to convert them to displacement field). It would be great if you could test it.

**Comment by prash-p** [comment] 2019-08-10 18:53
@lassoan While I get Bspline transform nodes in Slicer now, there are 2 other big issues:

The transform nodes written to Slicer no longer match the displacement field created by Elastix. This is evident if you do a (Translation, Euler, BSpline) registration and create an output volume via Elastix. The output volume and the input volume transformed by the transform node don't align. I believe that this is partly because you are now writing the fixedToMoving transform instead of movingToFixed as before (line 602)? I'm not sure why that has changed from the last commit, especially as the transform is now applied to the moving volume. This is also true for the BSpline transform although I don't know where the issue is in the code.

The second problem is that for some reason I still sometimes get displacement field transforms instead of Slicer Linear or BSpline transforms - even if I haven't checked the 'force grid output transform' box. The odd thing is that this doesn't always happen, unless I am doing a "TranslationTransform". Could the issue be line 335 where the registerVolumes function is being run with the checkbox no matter what?

All of this was tested in 4.10.2

**Comment by lassoan** [comment] 2019-08-11 02:46
> The transform nodes written to Slicer no longer match the displacement field created by Elastix. 

I've tested this with a recent Slicer Preview version with the default registration preset that uses Euler and Bspline and it worked well. **Could you please provide instructions of how to reproduce the mismatch? If possible, use sample data available in Slicer's SampleData module.** There could be slight differences in how the dense displacement field is computed from the sparse bspline grid  (e.g., ITK abruptly cuts off displacement outside the bspline grid, while VTK provide nice, smooth, invertible displacement field near and outside the bspline grid).

> I believe that this is partly because you are now writing the fixedToMoving transform instead of movingToFixed as before (line 602)?

The current transformation direction should be correct. You can verify this by inspecting the variable names and operations that create them.

Elastix (and most image-based registration methods) provide resampling transform = from fixed to moving  = transform (of moving image) from parent (fixed image). In case of linear transform, it was easy to compute the inverse (see the inversion step to get "moving to fixed" transform from the "fixed to moving" [here](https://github.com/lassoan/SlicerElastix/blob/4fc5d648a00f10640181c4f2bfd00e4cf07d0a45/Elastix/Elastix.py#L597-L598), I should remove line 597). However, for bspline transforms, inversion is not that simple, so switched everything to use "from parent" to avoid the need for any inversion.

> The second problem is that for some reason I still sometimes get displacement field transforms instead of Slicer Linear or BSpline transforms

If the module encounters an unknown transform type (anything other than "EulerTransform", "TranslationTransform", "BSplineTransform") then it will automatically revert to using grid transform (a.k.a. displacement field).

> even if I haven't checked the 'force grid output transform' box. 

If you check 'force grid output transform' checkbox then it forces the module to use grid transform, even if it could possibly load linear/bspline transforms. **Did you encounter any situation when you got non-grid transform when 'force grid output transform' was checked? Has reading of "EulerTransform", "TranslationTransform", "BSplineTransform" files failed for you?**

**Comment by prash-p** [comment] 2019-08-11 03:13
Okay, I will test it again in a Preview version and see if I can recreate the issue - but I shouldn't be having errors in 4.10 either way right?

> Has reading of "EulerTransform", "TranslationTransform", "BSplineTransform" files failed for you?

Yes, I received a displacement field when the 'force grid output transform' was **not** checked and while using a "TranslationTransform"

**Comment by lassoan** [comment] 2019-08-11 03:16
Yes, it should work with Slicer-4.10.2, too. I did a quick test with Slicer-4.10.2: registered MRBrainTumor1 and MRBrainTumor2 with "generic (all)" preset - and everything worked perfectly.

**Comment by lassoan** [comment] 2019-08-11 03:35
> Yes, I received a displacement field when the 'force grid output transform' was not checked and while using a "TranslationTransform"

I haven't tested TranslationTransform. Could you debug it and see why TranslationTransform is not recognized?

Which preset did you use?

**Comment by prash-p** [comment] 2019-08-11 21:34
Will do in the next few days. In the meantime here is the test parameter file I have been working with (I change the Transform line to either Euler, Translation or BSpline.


```
// *********************
// * ImageTypes
// *********************
(FixedInternalImagePixelType "float")
(FixedImageDimension 3)
(MovingInternalImagePixelType "float")
(MovingImageDimension 3)

// *********************
// * Components
// *********************
(Registration "MultiResolutionRegistration" )
(FixedImagePyramid "FixedRecursiveImagePyramid")
(MovingImagePyramid "MovingRecursiveImagePyramid")
(Interpolator "LinearInterpolator")
// (Metric "AdvancedMattesMutualInformation")
(Metric "AdvancedNormalizedCorrelation")
(Optimizer "AdaptiveStochasticGradientDescent")
// (Optimizer "RegularStepGradientDescent")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(Transform "EulerTransform")
(UseDirectionCosines "true")

// ******************* Similarity measure *********************

// Number of grey level bins in each resolution level,
// for the mutual information. 16 or 32 usually works fine.
// You could also employ a hierarchical strategy:
(NumberOfHistogramBins 16)


// If you use a mask, this option is important. 
// If the mask serves as region of interest, set it to false.
// If the mask indicates which pixels are RequiredRatioOfValidSamples, then set it to true.
// If you do not use a mask, the option doesn't matter.
//(ErodeMask "false")

(UseFastAndLowMemoryVersion "true")
(ShowExactMetricValue "false")

// **************** Image sampling **********************

// Number of spatial samples used to compute the mutual
// information (and its derivative) in each iteration.
// With an AdaptiveStochasticGradientDescent optimizer,
// in combination with the two options below, around 2000
// samples may already suffice.
(RequiredRatioOfValidSamples 0.01)
(NumberOfSpatialSamples 10000)
(MaximumNumberOfSamplingAttempts 10)
(AutomaticParameterEstimation "true")

// Refresh these spatial samples in every iteration, and select
// them randomly. See the manual for information on other sampling
// strategies.
(NewSamplesEveryIteration "true")
(ImageSampler "RandomCoordinate")


// ***************** Transformation **************************

// Scales the rotations compared to the translations, to make
// sure they are in the same range. In general, it's best to  
// use automatic scales estimation:
(AutomaticScalesEstimation "true")

// Automatically guess an initial translation by aligning the
// geometric centers of the fixed and moving.
(AutomaticTransformInitialization "true")
(AutomaticTransformInitializationMethod "CenterOfGravity")

// Whether transforms are combined by composition or by addition.
// In generally, Compose is the best option in most cases.
// It does not influence the results very much.
(HowToCombineTransforms "Compose")
(ComputeZYX "true")

// ******************* Optimizer ****************************

// Maximum number of iterations in each resolution level:
// 200-500 works usually fine for rigid registration.
// For more robustness, you may increase this to 1000-2000.
(MaximumNumberOfIterations 1000)

// The step size of the optimizer, in mm. By default the voxel size is used.
// which usually works well. In case of unusual high-resolution images
// (eg histology) it is necessary to increase this value a bit, to the size
// of the "smallest visible structure" in the image:
(MinimumStepLength 0.00001)
(MaximumStepLength 1)
//(NumberOfGradientMeasurements 10)

// *********************
// * Pyramid settings
// *********************
// The number of resolutions. 1 Is only enough if the expected
// deformations are small. 3 or 4 mostly works fine. For large
// images and large deformations, 5 or 6 may even be useful.
(NumberOfResolutions 1)
// The downsampling/blurring factors for the image pyramids.
// By default, the images are downsampled by a factor of 2
// compared to the next resolution.
// So, in 2D, with 4 resolutions, the following schedule is used:
//(ImagePyramidSchedule 2 2  1 1  .1 .1 )
// And in 3D:

//(ImagePyramidSchedule 10 10 10  6 6 4  4 4 2  2 2 1  1 1 0.5)
(ImagePyramidSchedule 4 4 2)


// Make sure that the number of elements equals the number
// of resolutions times the image dimension.



// *********************
// * Output settings
// *********************
// ************* Interpolation and Resampling ****************
//Default pixel value for pixels that come from outside the picture:
(DefaultPixelValue 0)

// Choose whether to generate the deformed moving image.
// You can save some time by setting this to false, if you are
// only interested in the final deformed moving image
// for example.
(WriteResultImage "false")

// The pixel type and format of the resulting deformed moving image
//(ResultImagePixelType "float")
//(ResultImageFormat "mhd")

```

**Comment by prash-p** [comment] 2019-08-12 20:52
@lassoan There are a couple of issues that I am still seeing. Testing in preview version

1. **I think the BSpline conversion is not accurate, and the error is more than just resampling differences between Slicer and Elastix.**
To recreate the error, download the CT-MR brain data from the download data module. Go to Elastix and register the MRBrainT1 (moving) to CTBrain (fixed) using the above parameter file (but change the transform to BSpline Transform). Select to create output volume and transform nodes. After registration, compare slice-by-slice the volume output by Elastix and the transformed volume in Slicer, especially at the end-beginning slice ranges. I think there are substantial differences in the results that are not explained just by resampling. (see attached [gif](https://drive.google.com/file/d/1UKOIuO6SdiBMPtVVl5x5tfY4tpoho-ht/view?usp=sharing) for visualization).

2. I confirmed that the rigid (euler) and translation transforms are working as expected on the sample data. However I the output euler transform does not work on my own data where the origins of the volumes may be 0. [I'm attaching two volumes](https://drive.google.com/file/d/1RRmflB-Cz6yjbSspqIwnV8-HikLqrmJq/view?usp=sharing) which you can use to see what I mean. Register US Dist (moving) to CT Dist (fixed) using the above parameter file (using EulerTransform), and create an output volume and output transform node. The output volume by Elastix does not (by a significant margin) match the Slicer transformed volume. I think we have to consider 'origin' from the output transform.txt files in Elastix when parsing. 

3. There was an issue with generating linear transform nodes when TranslationTransforms were being used, since computeZYX is not a parameter in these situations. I've fixed this by only considering computeZYX when it is a EulerTransform and not a TranslationTransform, and will create a pull request shortly.

**Comment by prash-p** [comment] 2019-08-13 23:44
For 2, I think the CentreOfRotationPoint parameter is not being considered properly. Do you know how to parse that appropriately into the linear node format?

**Comment by lassoan** [comment] 2019-08-14 03:46
It seems that indeed when transform parameters are set, `ComputeMatrix()` and `ComputeOffset()` methods are called (see https://github.com/SuperElastix/elastix/blob/d01e9c4eed2ef2641d852d169209b2c3c5d84976/Common/Transforms/itkAdvancedEuler3DTransform.hxx#L106-L117) and `ComputeOffset()` actually uses center of rotation for computing the translation part of the transformation matrix (see https://github.com/SuperElastix/elastix/blob/0ce6c24a2b74c0132f1a53848321f1c7a92162ea/Common/Transforms/itkAdvancedMatrixOffsetTransformBase.hxx#L493-L509).

Please update the transformation matrix computation accordingly and let me know if it fixes the problems you found.

**Comment by prash-p** [comment] 2019-08-14 19:50
Addressed points 2 and 3 above here: #22

**Comment by lassoan** [comment] 2019-09-14 01:24
BSpline and linear transform reading should work well now.

**Closed as completed by lassoan** 2019-09-14 01:24 UTC

**Comment by hbraunDSP** [comment] 2019-10-29 20:19
I'd like to add an already calculated elastix transform file to Slicer, and this thread seems to imply that it should Just Work. However, when I try to add the file to Slicer using the "Add Data" screen, it fails almost silently. This is the only indication that something went wrong:
```
Failed to read transform from file: /path/to/my/TransformParameters.0.txt
```
I just tried it with the latest nightly build of Slicer and a new install of SlicerElastix. Any advice? Is there some alternate way to load Slicer transforms that knows about this feature?
